---
NoRubocop/NoExtendTSig:
  Description: 'Do not `extend T::Sig`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoSig:
  Description: 'Do not define type signatures with `sig`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoTAbsurd:
  Description: 'Do not use `T.absurd`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoTEnum:
  Description: 'Do not inherit from `T::Enum`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoTStruct:
  Description: 'Do not inherit from `T::Struct`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoTypeAliases:
  Description: 'Do not alias types with `T.type_alias`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoTypeAnnotations:
  Description: 'Do not use type annotations with `T.let`'
  Enabled: true
  VersionAdded: '<<next>>'

NoRubocop/NoTypeAssertions:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'

NoRubocop/NoTypedSigil:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'
