---
NoSorbet/NoAbstractBang:
  Description: 'TODO: Write a description of the cop.'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoExtendTHelpers:
  Description: 'TODO: Write a description of the cop.'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoExtendTSig:
  Description: 'Do not `extend T::Sig`'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoInterfaceBang:
  Description: 'TODO: Write a description of the cop.'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoRequireSorbetRuntime:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'

NoSorbet/NoSig:
  Description: 'Do not define type signatures with `sig`'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoTAbsurd:
  Description: 'Do not use `T.absurd`'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoTEnum:
  Description: 'Do not inherit from `T::Enum`'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoTStruct:
  Description: 'Do not inherit from `T::Struct`'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoTypeAliases:
  Description: 'Do not alias types with `T.type_alias`'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoTypeAssertions:
  Description: 'Do not use type assertions `T.cast`, `T.must`, etc'
  Enabled: true
  VersionAdded: '<<next>>'

NoSorbet/NoTypedSigil:
  Description: 'Do not set the `typed` sigil'
  Enabled: true
  VersionAdded: '<<next>>'
